// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4LLAFDiW6zumePuYb7uWvGLz3WScBf0',
    appId: '1:453673117871:web:f6e4e04375b0233c7e8c5a',
    messagingSenderId: '453673117871',
    projectId: 'chaltapay-app',
    authDomain: 'chaltapay-app.firebaseapp.com',
    storageBucket: 'chaltapay-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_UUc3cK94ONfXv6zlqtCn1q7J8mMH2Bk',
    appId: '1:453673117871:android:41c6b7daa2c0792f7e8c5a',
    messagingSenderId: '453673117871',
    projectId: 'chaltapay-app',
    storageBucket: 'chaltapay-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb59jSh15hTguQFqkLgC4zENr9M8Zi6Y4',
    appId: '1:453673117871:ios:04158cfb296ae8317e8c5a',
    messagingSenderId: '453673117871',
    projectId: 'chaltapay-app',
    storageBucket: 'chaltapay-app.firebasestorage.app',
    iosBundleId: 'com.chaltapay.chaltapay',
  );
}
